### ISSUE TITLE
Larger margins

### ISSUE THREAD

**Issue by Livijn** [alexbowers/nova-categorise-resources#1]
I would prefer if you used `ml-4` instead of `ml-6` on the Categories. It makes it easier to see what's a category and whats a resource. Also, there needs to be a larger margin to the next tool. 

As you can see here, the categories are closer to "Roles and Permission" than "Resources".
![pic](https://i.gyazo.com/838290c0c8bb9ae888b58a8aade7f189.png)

**Comment by alexbowers** [comment]
Thoughts on latest release? 

https://github.com/alexbowers/nova-categorise-resources/releases/tag/v1.0.4

**Comment by alexbowers** [comment]
This package is now deprecated due to support in core Nova 1.0.18+
