### ISSUE TITLE
Chinese category name displays blank

### ISSUE THREAD

**Issue by phoenixg** [alexbowers/nova-categorise-resources#7]

**Comment by alexbowers** [comment]
Can you provide the name you are using so I can test it out?

**Comment by phoenixg** [comment]
@alexbowers Sure, please try out '目录名称';

**Comment by alexbowers** [comment]
Thanks, I'll get back to you this evening.

**Comment by alexbowers** [comment]
![image](https://user-images.githubusercontent.com/842974/45652254-e94c0180-bacb-11e8-90ab-1df9e18f7007.png)

@phoenixg It seems to work for me.

What part of it isn't working for you?

**Comment by alexbowers** [comment]
`public static $category = '目录名称';`

**Comment by phoenixg** [comment]
@alexbowers Oh I've tried again, it's really working for Chinese. Sorry to bother.

**Comment by alexbowers** [comment]
No problem. Thanks for trying out the project :)
